
package com.bayeesoft.AccFinService.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FCUBSAccFinService", targetNamespace = "http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com", wsdlLocation = "http://10.1.12.71:8101/FCUBSAccFinService/FCUBSAccFinService?WSDL")
public class FCUBSAccFinService
    extends Service
{

    private static final URL FCUBSACCFINSERVICE_WSDL_LOCATION;
    private static final WebServiceException FCUBSACCFINSERVICE_EXCEPTION;
    private static final QName FCUBSACCFINSERVICE_QNAME = new QName("http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com", "FCUBSAccFinService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.12.71:8101/FCUBSAccFinService/FCUBSAccFinService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCUBSACCFINSERVICE_WSDL_LOCATION = url;
        FCUBSACCFINSERVICE_EXCEPTION = e;
    }

    public FCUBSAccFinService() {
        super(__getWsdlLocation(), FCUBSACCFINSERVICE_QNAME);
    }

    public FCUBSAccFinService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCUBSACCFINSERVICE_QNAME, features);
    }

    public FCUBSAccFinService(URL wsdlLocation) {
        super(wsdlLocation, FCUBSACCFINSERVICE_QNAME);
    }

    public FCUBSAccFinService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCUBSACCFINSERVICE_QNAME, features);
    }

    public FCUBSAccFinService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCUBSAccFinService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCUBSAccFinServiceSEI
     */
    @WebEndpoint(name = "FCUBSAccFinServiceSEI")
    public FCUBSAccFinServiceSEI getFCUBSAccFinServiceSEI() {
        return super.getPort(new QName("http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com", "FCUBSAccFinServiceSEI"), FCUBSAccFinServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCUBSAccFinServiceSEI
     */
    @WebEndpoint(name = "FCUBSAccFinServiceSEI")
    public FCUBSAccFinServiceSEI getFCUBSAccFinServiceSEI(WebServiceFeature... features) {
        return super.getPort(new QName("http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com", "FCUBSAccFinServiceSEI"), FCUBSAccFinServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCUBSACCFINSERVICE_EXCEPTION!= null) {
            throw FCUBSACCFINSERVICE_EXCEPTION;
        }
        return FCUBSACCFINSERVICE_WSDL_LOCATION;
    }

}
