
package com.techstack.corebanking.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FCUBSAccFinServiceSEI", targetNamespace = "http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSAccFinServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.AccFinService.stub.REQUESTACCSTMTIOFSRES
     */
    @WebMethod(operationName = "RequestAccStmtIO")
    @WebResult(name = "REQUESTACCSTMT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccFinService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com/FCUBSAccFinServiceSEI/RequestAccStmtIORequest", output = "http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com/FCUBSAccFinServiceSEI/RequestAccStmtIOResponse")
    public REQUESTACCSTMTIOFSRES requestAccStmtIO(
        @WebParam(name = "REQUESTACCSTMT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccFinService", partName = "RequestMsg")
        REQUESTACCSTMTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.AccFinService.stub.QUERYFINANCIALCYCLEIOFSRES
     */
    @WebMethod(operationName = "QueryFinancialCycleIO")
    @WebResult(name = "QUERYFINANCIALCYCLE_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccFinService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com/FCUBSAccFinServiceSEI/QueryFinancialCycleIORequest", output = "http://FCUBSAccFinService.types.ws.gw.fcubs.ofss.com/FCUBSAccFinServiceSEI/QueryFinancialCycleIOResponse")
    public QUERYFINANCIALCYCLEIOFSRES queryFinancialCycleIO(
        @WebParam(name = "QUERYFINANCIALCYCLE_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccFinService", partName = "RequestMsg")
        QUERYFINANCIALCYCLEIOFSREQ requestMsg);

}
